image:
  resize:
  - 1920
  - 1080
model:
  classifications_path: classifications.txt
  flattened_images_path: flattened_images.txt
  k_value: 1
plate:
  Max_char: 0.09
  Min_char: 0.01
  RESIZED_IMAGE_HEIGHT: 30
  RESIZED_IMAGE_WIDTH: 20
preprocess:
  ADAPTIVE_THRESH_BLOCK_SIZE: 19
  ADAPTIVE_THRESH_WEIGHT: 9
  GAUSSIAN_SMOOTH_FILTER_SIZE:
  - 5
  - 5
